import { Star, Flame, Users, UserPlus, Upload, Share2, Bot, CalendarHeart, ImagePlay, Mic2, MessageCircleHeart } from "lucide-react";
import type { LandingContent } from "./types";

export const enContent: LandingContent = {
  lang: "en",
  nav: {
    features: "Features",
    pricing: "Pricing",
    faq: "FAQ",
    cta: "Get started free",
  },
  hero: {
    badge: "Preserve the memory of those you love",
    h1Line1: "Digital Memorial",
    h1Accent: "for those",
    h1Line3: "you love",
    p: "Upload photos, videos and voice recordings. AI avatar and chatbot let your family feel the presence of your loved one again",
    ctaPrimary: "Create a memorial for free",
    ctaSecondary: "Learn more",
    trustText: "12,000+ families have already created a memorial",
  },
  stats: [
    { value: "4.9", label: "average rating from families", icon: Star },
    { value: "12K+", label: "memorial pages created", icon: Flame },
    { value: "98%", label: "families recommend", icon: Users },
  ],
  howItWorks: {
    badge: "How it works",
    h2Line1: "Three steps to",
    h2Accent: "eternal memory",
    steps: [
      {
        num: "01",
        icon: UserPlus,
        title: "Create a memorial",
        desc: "Fill in the name, dates, biography — it takes just 5 minutes",
        img: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=280&fit=crop&q=80",
      },
      {
        num: "02",
        icon: Upload,
        title: "Upload memories",
        desc: "Photos, videos, voice recordings, letters and diaries",
        img: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=280&fit=crop&q=80",
      },
      {
        num: "03",
        icon: Share2,
        title: "Share with family",
        desc: "Send the link — relatives can add memories without registration",
        img: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400&h=280&fit=crop&q=80",
      },
    ],
  },
  features: {
    badge: "Features",
    h2Line1: "Keep everything,",
    h2Accent: "in one place",
    items: [
      { num: "01", icon: Bot, title: "AI Avatar", desc: "Upload a few photos — the service creates an animated video avatar that moves and speaks in your loved one's voice" },
      { num: "02", icon: Users, title: "Family Access", desc: "Share a unique link with relatives. Anyone can add memories, photos and stories — no account required" },
      { num: "03", icon: CalendarHeart, title: "Biography", desc: "Name, birth and passing dates, hometown, education, profession — create a full biographical page" },
      { num: "04", icon: ImagePlay, title: "Media Archive", desc: "Upload photos, videos, voice messages and documents. Everything is stored securely and accessible to the whole family" },
      { num: "05", icon: Mic2, title: "Voice Synthesis", desc: "Upload audio recordings — ElevenLabs clones the voice. The avatar will speak in your loved one's real voice" },
      { num: "06", icon: MessageCircleHeart, title: "AI Chatbot", desc: "Upload texts, letters, diaries — AI learns to respond as your loved one would have" },
    ],
  },
  testimonials: {
    badge: "Testimonials",
    h2Line1: "What families",
    h2Accent: "are saying",
    items: [
      { name: "Maria", text: "After losing my father, I didn't know how to preserve his memory for my children. Memory Diary helped create a page where grandchildren can get to know their grandfather through his photos, voice, and stories." },
      { name: "Alex", text: "We uploaded old cassettes with my grandmother's voice. The AI reproduced her intonations so accurately that my mother couldn't hold back tears. It's something incredible." },
      { name: "Svetlana", text: "My brothers and sisters live in different cities. Through one link, everyone added their memories and photos. No registration — just open and write." },
      { name: "Dmitry", text: "The chatbot replies with phrases my dad might have said. At first it felt strange, but then I understood — it's a way not to forget his wisdom and humor." },
      { name: "Elena", text: "Setting up the memorial took half an hour. The interface is intuitive, support responded in 10 minutes. I recommend it to anyone who wants to preserve memory with dignity." },
      { name: "Igor", text: "We created a memorial page for my grandfather, a veteran. Now it's a family archive for the whole lineage. Grandchildren will know what kind of person he was." },
    ],
  },
  pricing: {
    badge: "Pricing",
    h2Line1: "Choose",
    h2Accent: "your plan",
    subtitle: "Start for free and expand your memorial's features as needed",
    popularLabel: "Popular",
    plans: [
      {
        name: "Free",
        price: "$0",
        period: "forever",
        features: ["1 memorial page", "Up to 100 photos", "Up to 5 videos", "Text memories", "Family access via link"],
        cta: "Create a memorial",
        featured: false,
      },
      {
        name: "Premium ⭐",
        price: "$9",
        period: "per month",
        features: ["Up to 5 memorial pages", "Unlimited media storage", "AI avatar from photos", "Voice synthesis (ElevenLabs)", "AI chatbot based on memories", "Priority support"],
        cta: "Try 14 days free",
        featured: true,
      },
      {
        name: "Family",
        price: "$19",
        period: "per month",
        features: ["Everything in Premium", "Unlimited pages", "Up to 20 co-authors", "Public memorial page", "Personal manager"],
        cta: "Contact us",
        featured: false,
      },
    ],
  },
  faq: {
    badge: "FAQ",
    h2Line1: "Common",
    h2Accent: "questions",
    items: [
      { q: "How do I create a memorial page?", a: "Register, click 'Create memorial' and fill in the basic details: name, dates, biography. Then upload photos, videos and memories. It takes between 10 and 30 minutes." },
      { q: "How does the AI avatar work?", a: "Upload several clear photos of the face. The service sends them to a video generation system (HeyGen / D-ID), which creates an animated avatar. For voice synthesis, upload audio recordings at least 1 minute long — ElevenLabs will clone the voice." },
      { q: "How does the AI chatbot work?", a: "Upload text memories, letters, diaries and stories about your loved one. The system processes them using semantic search and trains a language model to respond in their style. The more texts — the more accurate the responses." },
      { q: "How is privacy ensured?", a: "The memorial page is private by default — accessible only via a unique link. Public mode is enabled manually. All uploaded media files and memories are encrypted at rest." },
      { q: "Do relatives need to register?", a: "No. The memorial creator generates a unique invite link. Relatives follow it and can immediately add memories, photos and comments without creating an account." },
    ],
  },
  cta: {
    h2Line1: "Create a memorial,",
    h2Accent: "while you remember every detail",
    p: "Free. No credit card. Memorial ready in 10 minutes.",
    btn: "Create a memorial for free",
  },
  waitlist: {
    h3: "Get early access",
    p: "Leave your email — we'll notify you about new features first",
    placeholder: "your@email.com",
    btn: "Get access",
    thanks: "Thank you, we'll be in touch!",
  },
  footer: {
    desc: "Digital memorials for preserving the memory of loved ones. AI avatar, voice synthesis and chatbot — all in one place.",
    col1: "About",
    col2: "Support",
    col3: "Resources",
    links1: ["Features", "Pricing", "FAQ"],
    links2: ["Help center", "Contact us", "Terms"],
    links3: ["Documentation", "GitHub"],
    copyright: "© 2025 Memory Diary. All rights reserved.",
    email: "support@memorydiary.ru",
  },
};
